# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC  # 数据库连接URL
    username: root  # 数据库用户名
    password: password # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL驱动程序类名
    type: com.alibaba.druid.pool.DruidDataSource  # 指定使用Druid连接池
    druid:
      initial-size: 5  # 初始化时建立物理连接的个数
      max-active: 20  # 最大连接池数量
      min-idle: 5  # 最小连接池数量
      max-wait: 60000  # 获取连接时最大等待时间，单位毫秒
      validation-query: SELECT 1 FROM DUAL  # 测试连接是否可用的SQL语句
      test-while-idle: true  # 保持连接池活跃地状态
      time-between-eviction-runs-millis: 60000  # 检查空闲连接的时间间隔，单位毫秒
      min-evictable-idle-time-millis: 300000  # 连接在连接池中最小空闲时间，单位毫秒
      filters: stat,wall,log4j2  # 配置Druid监控和防御SQL注入的过滤器
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml # Mapper.xml文件所在路径
  typeAliasesPackage: com.example.demo1.domain # 实体类包名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志输出方式
    map-underscore-to-camel-case: true # 开启驼峰命名规则映射
